version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - "./volumes/postgres:/var/lib/postgresql"

  pgadmin:
   image: dpage/pgadmin4:6.15
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
     PGADMIN_DEFAULT_PASSWORD: admin
     PGADMIN_LISTEN_PORT: 82
   ports:
    - "8282:82"
